# Site settings
title: Web-Log
email: caglar.gonul.001@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming languages notes are mostly taken from the MOOC course named Programming Languages by Dan Grossman.

baseurl: "" # the subpath of your site, e.g. /blog/  
url: "http://localhost:4000"
twitter_username: caglar_gonul
github_username:  cgonul
linkedin_username : caglargonul

# Build settings
markdown: kramdown
highlighter: rouge

paginate: 5

permalink: /:categories/:title

