# Site settings
title: Programming Languages Notes
email: caglar.gonul.001@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My programming languages notes mostly taken from the MOOC course named Programming Languages by Dan Grossman.
twitter_username: caglar_gonul
github_username:  cgonul

# Build settings
markdown: kramdown
highlighter: rouge
